POST http://localhost:3000/user/create
content-type: application/json

{
    "firstName":"Naveen",
    "lastName":"Singh",
    "userName":"Singh@test.com",
    "gender":"male",
    "dob":"1998-06-25"
}



### Find all users with a given userName
GET http://localhost:3000/user/findAll?userName=Vivek@test.com



### Find a particular user with a given ID
GET http://localhost:3000/user/1


### update a user
PATCH http://localhost:3000/user/1
Content-Type: application/json

{
    "userName":"abc@abc.com"
}


### Deleting User By Id
DELETE http://localhost:3000/user/1