POST http://localhost:3000/user/create
content-type: application/json

{
    "firstName":"Rahul",
    "lastName":"Kumar",
    "userName":"Rahul@test.com",
    "gender":"male",
    "dob":"19/07/1999"
}



### Find all users with a given userName
GET http://localhost:3000/user/findAll?userName=Rahul@test.com



### Find a particular user with a given ID
GET http://localhost:3000/user/1


### update a user
PATCH http://localhost:3000/user/1
Content-Type: application/json

{
    "userName":"abc@abc.com"
}
